export {default as Home} from './Home'
export {default as About} from './About'
export {default as Blogs} from './Blogs'
export {default as Contact} from './Contact'
export {default as Menu} from './Menu'
export {default as Products} from './Products'
export {default as Review} from './Review'